"""Enumerations for configuration / metadata layer."""

import enum


class CustomFieldType(str, enum.Enum):
    TEXT = "TEXT"
    LONG_TEXT = "LONG_TEXT"
    INTEGER = "INTEGER"
    DECIMAL = "DECIMAL"
    BOOLEAN = "BOOLEAN"
    DATE = "DATE"
    DATETIME = "DATETIME"
    SELECT = "SELECT"
    MULTI_SELECT = "MULTI_SELECT"
    URL = "URL"
    EMAIL = "EMAIL"
    REFERENCE = "REFERENCE"


class ConfigAuditAction(str, enum.Enum):
    CUSTOM_FIELD_CREATED = "CUSTOM_FIELD_CREATED"
    CUSTOM_FIELD_UPDATED = "CUSTOM_FIELD_UPDATED"
    CUSTOM_FIELD_DISABLED = "CUSTOM_FIELD_DISABLED"
    MODULE_ENABLED = "MODULE_ENABLED"
    MODULE_DISABLED = "MODULE_DISABLED"
    REQUIREMENT_CONFIGURED = "REQUIREMENT_CONFIGURED"
    SETTING_UPDATED = "SETTING_UPDATED"
    INTEGRATION_CREATED = "INTEGRATION_CREATED"
    INTEGRATION_MODIFIED = "INTEGRATION_MODIFIED"
    INTEGRATION_TESTED = "INTEGRATION_TESTED"
    INTEGRATION_DISABLED = "INTEGRATION_DISABLED"
