"""configuration_metadata_layer

Revision ID: 3919f2be7fdd
Revises: 003_evidence_storage_neutral
Create Date: 2026-09-29 10:09:36.226048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3919f2be7fdd'
down_revision: Union[str, None] = '003_evidence_storage_neutral'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(length=256), nullable=False),
    sa.Column('action', postgresql.ENUM('CUSTOM_FIELD_CREATED', 'CUSTOM_FIELD_UPDATED', 'CUSTOM_FIELD_DISABLED', 'MODULE_ENABLED', 'MODULE_DISABLED', 'REQUIREMENT_CONFIGURED', 'SETTING_UPDATED', name='config_audit_action'), nullable=False),
    sa.Column('object_type', sa.String(length=128), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_configuration_audit_log_created_at', 'configuration_audit_log', ['created_at'], unique=False)
    op.create_index('ix_configuration_audit_log_financial_entity_id', 'configuration_audit_log', ['financial_entity_id'], unique=False)
    op.create_index('ix_configuration_audit_log_object', 'configuration_audit_log', ['object_type', 'object_id'], unique=False)
    op.create_table('dora_domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('platform_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_defined', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('custom_field_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('field_type', postgresql.ENUM('TEXT', 'LONG_TEXT', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'DATE', 'DATETIME', 'SELECT', 'MULTI_SELECT', 'URL', 'EMAIL', 'REFERENCE', name='custom_field_type'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('default_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_entity_id'], ['financial_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_entity_id', 'entity_type', 'field_key', name='uq_custom_field_key_per_org_entity')
    )
    op.create_index('ix_custom_field_definitions_active', 'custom_field_definitions', ['active'], unique=False)
    op.create_index('ix_custom_field_definitions_entity_type', 'custom_field_definitions', ['entity_type'], unique=False)
    op.create_index('ix_custom_field_definitions_financial_entity_id', 'custom_field_definitions', ['financial_entity_id'], unique=False)
    op.create_table('dora_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_immutable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['dora_domains.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_dora_requirement_code')
    )
    op.create_index('ix_dora_requirements_domain_id', 'dora_requirements', ['domain_id'], unique=False)
    op.create_table('organization_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('platform_module_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_entity_id'], ['financial_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_module_id'], ['platform_modules.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_entity_id', 'platform_module_id', name='uq_org_module')
    )
    op.create_index('ix_organization_modules_enabled', 'organization_modules', ['enabled'], unique=False)
    op.create_index('ix_organization_modules_financial_entity_id', 'organization_modules', ['financial_entity_id'], unique=False)
    op.create_table('organization_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('setting_key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_entity_id'], ['financial_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_entity_id', 'setting_key', name='uq_org_setting_key')
    )
    op.create_index('ix_organization_settings_financial_entity_id', 'organization_settings', ['financial_entity_id'], unique=False)
    op.create_table('custom_field_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('field_definition_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_definition_id'], ['custom_field_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_entity_id'], ['financial_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_definition_id', 'entity_type', 'entity_id', name='uq_custom_field_value_entity')
    )
    op.create_index('ix_custom_field_values_entity', 'custom_field_values', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_custom_field_values_field_definition_id', 'custom_field_values', ['field_definition_id'], unique=False)
    op.create_index('ix_custom_field_values_financial_entity_id', 'custom_field_values', ['financial_entity_id'], unique=False)
    op.create_table('organization_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('dora_requirement_id', sa.UUID(), nullable=False),
    sa.Column('applicable', sa.Boolean(), nullable=False),
    sa.Column('implementation_status', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dora_requirement_id'], ['dora_requirements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_entity_id'], ['financial_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_entity_id', 'dora_requirement_id', name='uq_org_requirement')
    )
    op.create_index('ix_organization_requirements_financial_entity_id', 'organization_requirements', ['financial_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organization_requirements_financial_entity_id', table_name='organization_requirements')
    op.drop_table('organization_requirements')
    op.drop_index('ix_custom_field_values_financial_entity_id', table_name='custom_field_values')
    op.drop_index('ix_custom_field_values_field_definition_id', table_name='custom_field_values')
    op.drop_index('ix_custom_field_values_entity', table_name='custom_field_values')
    op.drop_table('custom_field_values')
    op.drop_index('ix_organization_settings_financial_entity_id', table_name='organization_settings')
    op.drop_table('organization_settings')
    op.drop_index('ix_organization_modules_financial_entity_id', table_name='organization_modules')
    op.drop_index('ix_organization_modules_enabled', table_name='organization_modules')
    op.drop_table('organization_modules')
    op.drop_index('ix_dora_requirements_domain_id', table_name='dora_requirements')
    op.drop_table('dora_requirements')
    op.drop_index('ix_custom_field_definitions_financial_entity_id', table_name='custom_field_definitions')
    op.drop_index('ix_custom_field_definitions_entity_type', table_name='custom_field_definitions')
    op.drop_index('ix_custom_field_definitions_active', table_name='custom_field_definitions')
    op.drop_table('custom_field_definitions')
    op.drop_table('platform_modules')
    op.drop_table('dora_domains')
    op.drop_index('ix_configuration_audit_log_object', table_name='configuration_audit_log')
    op.drop_index('ix_configuration_audit_log_financial_entity_id', table_name='configuration_audit_log')
    op.drop_index('ix_configuration_audit_log_created_at', table_name='configuration_audit_log')
    op.drop_table('configuration_audit_log')
    # ### end Alembic commands ###
