"""initial_schema

Revision ID: 774dec1bcf90
Revises: 
Create Date: 2026-09-28 08:58:59.737006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '774dec1bcf90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', postgresql.ENUM('create', 'update', 'delete', 'approve', 'reject', 'generate_roi', name='audit_action'), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_records_created_at', 'audit_records', ['created_at'], unique=False)
    op.create_index('ix_audit_records_entity', 'audit_records', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_records_financial_entity_id', 'audit_records', ['financial_entity_id'], unique=False)
    op.create_table('document_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('dora_control_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('financial_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=512), nullable=False),
    sa.Column('short_name', sa.String(length=256), nullable=True),
    sa.Column('lei', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('business_functions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('critical_or_important', postgresql.ENUM('critical', 'important', 'neither', name='critical_or_important'), nullable=False),
    sa.Column('function_identifier', sa.String(length=128), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'under_review', name='business_function_status'), nullable=False),
    sa.Column('exit_strategy_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_entity_id'], ['financial_entities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_entity_id', 'function_identifier', name='uq_function_identifier_per_entity')
    )
    op.create_index('ix_business_functions_criticality', 'business_functions', ['critical_or_important'], unique=False)
    op.create_index('ix_business_functions_financial_entity_id', 'business_functions', ['financial_entity_id'], unique=False)
    op.create_table('ict_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=512), nullable=False),
    sa.Column('trading_name', sa.String(length=512), nullable=True),
    sa.Column('lei', sa.String(length=20), nullable=True),
    sa.Column('euid', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('provider_type', postgresql.ENUM('ict_third_party', 'intra_group', 'cloud_service', 'software_vendor', 'other', name='provider_type'), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'onboarding', 'offboarding', 'suspended', name='provider_status'), nullable=False),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("country_code ~ '^[A-Z]{2}$'", name='ck_provider_country_iso2'),
    sa.CheckConstraint("lei IS NULL OR (char_length(lei) = 20 AND lei ~ '^[A-Z0-9]{20}$')", name='ck_provider_lei_format'),
    sa.ForeignKeyConstraint(['financial_entity_id'], ['financial_entities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_entity_id', 'lei', name='uq_provider_lei_per_entity'),
    sa.UniqueConstraint('id', 'financial_entity_id', name='uq_provider_id_entity')
    )
    op.create_index('ix_ict_providers_financial_entity_id', 'ict_providers', ['financial_entity_id'], unique=False)
    op.create_index('ix_ict_providers_legal_name', 'ict_providers', ['legal_name'], unique=False)
    op.create_index('ix_ict_providers_lei', 'ict_providers', ['lei'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(length=128), nullable=False),
    sa.Column('contract_type', postgresql.ENUM('master_services', 'subscription', 'license', 'outsourcing', 'other', name='contract_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('governing_law', sa.String(length=128), nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'active', 'expired', 'terminated', 'pending_renewal', name='contract_status'), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('termination_notice_period_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR start_date <= end_date', name='ck_contract_date_range'),
    sa.ForeignKeyConstraint(['financial_entity_id'], ['financial_entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id', 'financial_entity_id'], ['ict_providers.id', 'ict_providers.financial_entity_id'], name='fk_contract_provider_same_entity', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_entity_id', 'reference_number', name='uq_contract_reference_per_entity'),
    sa.UniqueConstraint('id', 'financial_entity_id', name='uq_contract_id_entity')
    )
    op.create_index('ix_contracts_end_date', 'contracts', ['end_date'], unique=False)
    op.create_index('ix_contracts_financial_entity_id', 'contracts', ['financial_entity_id'], unique=False)
    op.create_index('ix_contracts_provider_id', 'contracts', ['provider_id'], unique=False)
    op.create_index('ix_contracts_reference_number', 'contracts', ['reference_number'], unique=False)
    op.create_table('subcontractors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('parent_subcontractor_id', sa.UUID(), nullable=True),
    sa.Column('legal_name', sa.String(length=512), nullable=False),
    sa.Column('lei', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('processing_location', sa.String(length=256), nullable=True),
    sa.Column('depth_rank', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'pending', name='subcontractor_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("country_code ~ '^[A-Z]{2}$'", name='ck_subcontractor_country_iso2'),
    sa.CheckConstraint("lei IS NULL OR (char_length(lei) = 20 AND lei ~ '^[A-Z0-9]{20}$')", name='ck_subcontractor_lei_format'),
    sa.CheckConstraint('(parent_subcontractor_id IS NULL AND depth_rank = 0) OR (parent_subcontractor_id IS NOT NULL AND depth_rank > 0)', name='ck_subcontractor_depth_consistency'),
    sa.ForeignKeyConstraint(['financial_entity_id'], ['financial_entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_subcontractor_id', 'provider_id'], ['subcontractors.id', 'subcontractors.provider_id'], name='fk_subcontractor_parent_same_provider', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id', 'financial_entity_id'], ['ict_providers.id', 'ict_providers.financial_entity_id'], name='fk_subcontractor_provider_same_entity', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'provider_id', name='uq_subcontractor_id_provider')
    )
    op.create_index('ix_subcontractors_financial_entity_id', 'subcontractors', ['financial_entity_id'], unique=False)
    op.create_index('ix_subcontractors_parent_id', 'subcontractors', ['parent_subcontractor_id'], unique=False)
    op.create_index('ix_subcontractors_provider_id', 'subcontractors', ['provider_id'], unique=False)
    op.create_table('contract_dora_controls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('control_definition_id', sa.UUID(), nullable=False),
    sa.Column('compliance_status', postgresql.ENUM('compliant', 'non_compliant', 'not_assessed', 'pending_review', name='compliance_status'), nullable=False),
    sa.Column('assessed_by', sa.String(length=256), nullable=True),
    sa.Column('approved_by', sa.String(length=256), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_suggested_status', postgresql.ENUM('compliant', 'non_compliant', 'not_assessed', 'pending_review', name='compliance_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id', 'financial_entity_id'], ['contracts.id', 'contracts.financial_entity_id'], name='fk_contract_control_same_entity', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['control_definition_id'], ['dora_control_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_entity_id'], ['financial_entities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'control_definition_id', name='uq_contract_control')
    )
    op.create_index('ix_contract_dora_controls_contract_id', 'contract_dora_controls', ['contract_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.Column('blob_uri', sa.String(length=2048), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=256), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_status', postgresql.ENUM('unverified', 'verified', 'rejected', 'expired', name='verification_status'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id', 'financial_entity_id'], ['contracts.id', 'contracts.financial_entity_id'], name='fk_evidence_contract_same_entity', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_entity_id'], ['financial_entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id', 'financial_entity_id'], ['ict_providers.id', 'ict_providers.financial_entity_id'], name='fk_evidence_provider_same_entity', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_expiry_date', 'evidence', ['expiry_date'], unique=False)
    op.create_index('ix_evidence_financial_entity_id', 'evidence', ['financial_entity_id'], unique=False)
    op.create_index('ix_evidence_provider_id', 'evidence', ['provider_id'], unique=False)
    op.create_table('ict_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('classification_id', sa.UUID(), nullable=True),
    sa.Column('data_processing_location', sa.String(length=256), nullable=True),
    sa.Column('data_storage_location', sa.String(length=256), nullable=True),
    sa.Column('data_location_country', sa.String(length=2), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'planned', 'decommissioned', name='service_status'), nullable=False),
    sa.Column('supports_critical_or_important', postgresql.ENUM('critical', 'important', 'neither', name='critical_or_important'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_location_country IS NULL OR data_location_country ~ '^[A-Z]{2}$'", name='ck_service_data_location_country'),
    sa.ForeignKeyConstraint(['classification_id'], ['service_classifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id', 'financial_entity_id'], ['contracts.id', 'contracts.financial_entity_id'], name='fk_service_contract_same_entity', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_entity_id'], ['financial_entities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'contract_id', name='uq_service_id_contract')
    )
    op.create_index('ix_ict_services_contract_id', 'ict_services', ['contract_id'], unique=False)
    op.create_index('ix_ict_services_financial_entity_id', 'ict_services', ['financial_entity_id'], unique=False)
    op.create_index('ix_ict_services_supports_cif', 'ict_services', ['supports_critical_or_important'], unique=False)
    op.create_table('evidence_control_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('contract_control_id', sa.UUID(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_control_id'], ['contract_dora_controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'contract_control_id', name='uq_evidence_control')
    )
    op.create_table('exit_strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('business_function_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('exit_objective', sa.Text(), nullable=False),
    sa.Column('alternative_provider_name', sa.String(length=512), nullable=True),
    sa.Column('migration_strategy', sa.Text(), nullable=True),
    sa.Column('rto_hours', sa.Integer(), nullable=True),
    sa.Column('rpo_hours', sa.Integer(), nullable=True),
    sa.Column('data_portability_notes', sa.Text(), nullable=True),
    sa.Column('dependencies_notes', sa.Text(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('test_result', postgresql.ENUM('not_tested', 'passed', 'failed', 'partial', name='exit_test_result'), nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'approved', 'tested', 'requires_update', name='exit_strategy_status'), nullable=False),
    sa.Column('primary_evidence_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_function_id'], ['business_functions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contract_id', 'financial_entity_id'], ['contracts.id', 'contracts.financial_entity_id'], name='fk_exit_contract_same_entity', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_entity_id'], ['financial_entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['primary_evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id', 'financial_entity_id'], ['ict_providers.id', 'ict_providers.financial_entity_id'], name='fk_exit_provider_same_entity', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['ict_services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exit_strategies_business_function_id', 'exit_strategies', ['business_function_id'], unique=False)
    op.create_index('ix_exit_strategies_financial_entity_id', 'exit_strategies', ['financial_entity_id'], unique=False)
    op.create_table('function_service_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('function_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['business_functions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['ict_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('function_id', 'service_id', name='uq_function_service')
    )
    op.create_index('ix_function_service_mappings_function_id', 'function_service_mappings', ['function_id'], unique=False)
    op.create_index('ix_function_service_mappings_service_id', 'function_service_mappings', ['service_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_entity_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('criticality', postgresql.ENUM('very_low', 'low', 'medium', 'high', 'very_high', name='risk_dimension_level'), nullable=False),
    sa.Column('data_sensitivity', postgresql.ENUM('very_low', 'low', 'medium', 'high', 'very_high', name='risk_dimension_level'), nullable=False),
    sa.Column('substitutability', postgresql.ENUM('very_low', 'low', 'medium', 'high', 'very_high', name='risk_dimension_level'), nullable=False),
    sa.Column('concentration_risk', postgresql.ENUM('very_low', 'low', 'medium', 'high', 'very_high', name='risk_dimension_level'), nullable=False),
    sa.Column('geographic_risk', postgresql.ENUM('very_low', 'low', 'medium', 'high', 'very_high', name='risk_dimension_level'), nullable=False),
    sa.Column('security_assurance', postgresql.ENUM('very_low', 'low', 'medium', 'high', 'very_high', name='risk_dimension_level'), nullable=False),
    sa.Column('contract_gaps', postgresql.ENUM('very_low', 'low', 'medium', 'high', 'very_high', name='risk_dimension_level'), nullable=False),
    sa.Column('exit_feasibility', postgresql.ENUM('very_low', 'low', 'medium', 'high', 'very_high', name='risk_dimension_level'), nullable=False),
    sa.Column('calculation_version', sa.String(length=32), nullable=False),
    sa.Column('resulting_risk_level', postgresql.ENUM('low', 'medium', 'high', 'critical', name='risk_level'), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assessor', sa.String(length=256), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.CheckConstraint('num_nonnulls(provider_id, contract_id, service_id) >= 1', name='ck_risk_assessment_target'),
    sa.ForeignKeyConstraint(['contract_id', 'financial_entity_id'], ['contracts.id', 'contracts.financial_entity_id'], name='fk_risk_contract_same_entity', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_entity_id'], ['financial_entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id', 'financial_entity_id'], ['ict_providers.id', 'ict_providers.financial_entity_id'], name='fk_risk_provider_same_entity', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['ict_services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_assessments_calculated_at', 'risk_assessments', ['calculated_at'], unique=False)
    op.create_index('ix_risk_assessments_financial_entity_id', 'risk_assessments', ['financial_entity_id'], unique=False)
    op.create_index('ix_risk_assessments_provider_id', 'risk_assessments', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_assessments_provider_id', table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_financial_entity_id', table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_calculated_at', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index('ix_function_service_mappings_service_id', table_name='function_service_mappings')
    op.drop_index('ix_function_service_mappings_function_id', table_name='function_service_mappings')
    op.drop_table('function_service_mappings')
    op.drop_index('ix_exit_strategies_financial_entity_id', table_name='exit_strategies')
    op.drop_index('ix_exit_strategies_business_function_id', table_name='exit_strategies')
    op.drop_table('exit_strategies')
    op.drop_table('evidence_control_links')
    op.drop_index('ix_ict_services_supports_cif', table_name='ict_services')
    op.drop_index('ix_ict_services_financial_entity_id', table_name='ict_services')
    op.drop_index('ix_ict_services_contract_id', table_name='ict_services')
    op.drop_table('ict_services')
    op.drop_index('ix_evidence_provider_id', table_name='evidence')
    op.drop_index('ix_evidence_financial_entity_id', table_name='evidence')
    op.drop_index('ix_evidence_expiry_date', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_contract_dora_controls_contract_id', table_name='contract_dora_controls')
    op.drop_table('contract_dora_controls')
    op.drop_index('ix_subcontractors_provider_id', table_name='subcontractors')
    op.drop_index('ix_subcontractors_parent_id', table_name='subcontractors')
    op.drop_index('ix_subcontractors_financial_entity_id', table_name='subcontractors')
    op.drop_table('subcontractors')
    op.drop_index('ix_contracts_reference_number', table_name='contracts')
    op.drop_index('ix_contracts_provider_id', table_name='contracts')
    op.drop_index('ix_contracts_financial_entity_id', table_name='contracts')
    op.drop_index('ix_contracts_end_date', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_ict_providers_lei', table_name='ict_providers')
    op.drop_index('ix_ict_providers_legal_name', table_name='ict_providers')
    op.drop_index('ix_ict_providers_financial_entity_id', table_name='ict_providers')
    op.drop_table('ict_providers')
    op.drop_index('ix_business_functions_financial_entity_id', table_name='business_functions')
    op.drop_index('ix_business_functions_criticality', table_name='business_functions')
    op.drop_table('business_functions')
    op.drop_table('service_classifications')
    op.drop_table('financial_entities')
    op.drop_table('dora_control_definitions')
    op.drop_table('document_types')
    op.drop_index('ix_audit_records_financial_entity_id', table_name='audit_records')
    op.drop_index('ix_audit_records_entity', table_name='audit_records')
    op.drop_index('ix_audit_records_created_at', table_name='audit_records')
    op.drop_table('audit_records')
    # ### end Alembic commands ###
